import{a as c,S as d,i}from"./assets/vendor-CrAdtshy.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const u="49001064-c7b72e374a4ae6399075933f6",p="https://pixabay.com/api/";function m(s){const o={key:u,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0};return c.get(p,{params:o}).then(t=>t.data.hits).catch(t=>{throw console.error("Error fetching images:",t),t})}function f(){document.querySelector(".loader").classList.remove("hidden")}function g(){document.querySelector(".loader").classList.add("hidden")}function y(){document.getElementById("gallery").innerHTML=""}function h(s){const o=document.getElementById("gallery");y(),s.forEach(n=>{const e=document.createElement("li");e.classList.add("gallery-item"),e.innerHTML=`
        <a href="${n.largeImageURL}" class="gallery-link">
            <img src="${n.webformatURL}" alt="${n.tags}" class="gallery-image" />
        </a>
        <div class="info">
            <p>Likes <span>${n.likes}</span></p>
            <p>Views <span>${n.views}</span></p>
            <p>Comments <span>${n.comments}</span></p>
            <p>Downloads <span>${n.downloads}</span></p>
        </div>
    `,o.appendChild(e)}),new d(".gallery-link",{captionsData:"alt"}).refresh()}const L=document.getElementById("search-form"),E=document.getElementById("search-input");document.querySelector(".loader");const l=document.getElementById("gallery");L.addEventListener("submit",async s=>{s.preventDefault();const o=E.value.trim();if(o===""){i.error({title:"Error",message:"Please enter a search query!",position:"topRight",pauseOnHover:!1,closeOnClick:!0});return}l.innerHTML="",f();try{const t=await m(o);t.length===0?i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",pauseOnHover:!1,closeOnClick:!0}):h(t)}catch{l.innerHTML="",i.error({title:"Error",message:"Something went wrong. Please try again later!",position:"topRight",pauseOnHover:!1,closeOnClick:!0})}finally{g()}});
//# sourceMappingURL=index.js.map
