import{a as c,S as d,i}from"./assets/vendor-CrAdtshy.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const p="49001064-c7b72e374a4ae6399075933f6",u="https://pixabay.com/api/";function f(o){const t={key:p,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0};return c.get(u,{params:t}).then(s=>s.data.hits).catch(s=>{throw console.error("Error fetching images:",s),new Error("Something went wrong. Please try again later!")})}function m(o){o.classList.remove("hidden")}function h(o){o.classList.add("hidden")}function g(o){const t=document.getElementById("gallery");t.innerHTML="",o.forEach(n=>{const e=document.createElement("li");e.classList.add("gallery-item"),e.innerHTML=`
        <a href="${n.largeImageURL}" class="gallery-link">
            <img src="${n.webformatURL}" alt="${n.tags}" class="gallery-image" />
        </a>
        <div class="info">
            <p>Likes <span>${n.likes}</span></p>
            <p>Views <span>${n.views}</span></p>
            <p>Comments <span>${n.comments}</span></p>
            <p>Downloads <span>${n.downloads}</span></p>
        </div>
    `,t.appendChild(e)}),new d(".gallery-link",{captionsData:"alt"}).refresh()}const y=document.getElementById("search-form"),L=document.getElementById("search-input"),l=document.querySelector(".loader");y.addEventListener("submit",o=>{o.preventDefault();const t=L.value.trim();if(t===""){i.error({title:"Error",message:"Please enter a search query!",position:"topRight",pauseOnHover:!1,closeOnClick:!0});return}m(l),f(t).then(s=>{s.length===0?i.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",pauseOnHover:!1,closeOnClick:!0}):(console.log(s),g(s))}).finally(()=>{h(l)})});
//# sourceMappingURL=index.js.map
