import{i as c,S as d,a as u}from"./assets/vendor-CQ2WEMzV.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const f=document.getElementById("search-form"),m=document.getElementById("search-input"),h="49001064-c7b72e374a4ae6399075933f6",g="https://pixabay.com/api/";function y(a){const r={key:h,q:a,image_type:"photo",orientation:"horizontal",safesearch:!0};return u.get(g,{params:r}).then(o=>o.data.hits).catch(o=>{console.error("Error fetching images:",o),c.error({title:"Error",message:"Something went wrong. Please try again later!",position:"topRight",pauseOnHover:!1,closeOnClick:!0})})}const p=document.querySelector(".loader");f.addEventListener("submit",a=>{a.preventDefault();const r=m.value.trim();if(r===""){c.error({title:"Error",message:"Please enter a search query!",position:"topRight",pauseOnHover:!1,closeOnClick:!0});return}i(),y(r).then(t=>{t.length===0?c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",pauseOnHover:!1,closeOnClick:!0}):(console.log(t),o(t))}).finally(()=>{e()});function o(t){const n=document.getElementById("gallery");n.innerHTML="",t.forEach(s=>{const l=document.createElement("li");l.classList.add("gallery-item"),l.innerHTML=`
        <a href="${s.largeImageURL}" class="gallery-link">
                <img src="${s.webformatURL}" alt="${s.tags}" class="gallery-image" />
            </a>
        <div class="info">
            <p>Likes <span>${s.likes}</span></p>
            <p>Views <span>${s.views}</span></p>
            <p>Comments <span>${s.comments}</span></p>
            <p>Downloads <span>${s.downloads}</span></p>
        </div>`,n.appendChild(l)}),new d(".gallery-link",{captionsData:"alt"}).refresh()}function i(){p.classList.remove("hidden")}function e(){p.classList.add("hidden")}});
//# sourceMappingURL=index.js.map
